/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package kelegram.server

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals
import io.ktor.server.testing.*
import io.ktor.http.*

class AppTest {
    @Test fun testGetMessage() {
        withTestApplication(App) {
            handleRequest(HttpMethod.Get, "/").apply {
                assertEquals(HttpStatusCode.OK, response.status())
                assertEquals("What did you learn?", response.content)
            }
        }
    }
}
